name: 05-2-Events Filters and Activity Types

on: 
  pull_request:
    types:
        - closed
    branches:
        - main
jobs:
  echo:
    runs-on: ubuntu-lates
    steps:
      - run: echo "Running whenever a PR is closed"