name: 02 - Workflow Events

on:
  schedule:
    - cron: "21 21 * * *"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps: 
      - name: show the trigger
        run: echo "I have been triggered by a(n) ${{ github.event_name }} event."
              